### ISSUE TITLE
panic building FST

### ISSUE THREAD

**Issue by mschoch** [couchbaselabs/vellum#9]
Input: first 1000 lines of sorted MacOS dictionary

<details>
A
Aani
Aaron
Aaronic
Aaronical
Aaronite
Aaronitic
Aaru
Ab
Ababdeh
Ababua
Abadite
Abama
Abanic
Abantes
Abarambo
Abaris
Abasgi
Abassin
Abatua
Abba
Abbadide
Abbasside
Abbie
Abby
Abderian
Abderite
Abdiel
Abdominales
Abe
Abel
Abelia
Abelian
Abelicea
Abelite
Abelmoschus
Abelonian
Abencerrages
Aberdeen
Aberdonian
Aberia
Abhorson
Abie
Abies
Abietineae
Abiezer
Abigail
Abipon
Abitibi
Abkhas
Abkhasian
Ablepharus
Abnaki
Abner
Abo
Abobra
Abongo
Abraham
Abrahamic
Abrahamidae
Abrahamite
Abrahamitic
Abram
Abramis
Abranchiata
Abrocoma
Abroma
Abronia
Abrus
Absalom
Absaroka
Absi
Absyrtus
Abu
Abundantia
Abuta
Abutilon
Abyssinian
Acacia
Acacian
Academic
Academus
Acadia
Acadian
Acadie
Acaena
Acalepha
Acalephae
Acalypha
Acalypterae
Acalyptrata
Acalyptratae
Acamar
Acanthaceae
Acantharia
Acanthia
Acanthocephala
Acanthocephali
Acanthocereus
Acanthodea
Acanthodei
Acanthodes
Acanthodidae
Acanthodii
Acanthodini
Acantholimon
Acanthomeridae
Acanthopanax
Acanthophis
Acanthopteri
Acanthopterygii
Acanthuridae
Acanthurus
Acarapis
Acarida
Acaridea
Acarina
Acarus
Acastus
Accipiter
Accipitres
Aceldama
Acemetae
Acemetic
Acephala
Acephali
Acephalina
Acephalite
Acer
Aceraceae
Acerae
Acerata
Acerates
Aceratherium
Acerbas
Acestes
Acetabularia
Acetobacter
Achaean
Achaemenian
Achaemenid
Achaemenidae
Achaemenidian
Achaenodon
Achaeta
Achagua
Achakzai
Achamoth
Achango
Achariaceae
Achariaceous
Achates
Achatina
Achatinella
Achatinidae
Achen
Achernar
Acheronian
Acherontic
Acherontical
Achetidae
Acheulean
Achillea
Achillean
Achilleid
Achillize
Achimenes
Achinese
Achitophel
Achlamydeae
Achmetha
Acholoe
Achomawi
Achordata
Achorion
Achras
Achroanthes
Achromatiaceae
Achromatium
Achromobacter
Achromobacterieae
Achuas
Achyranthes
Achyrodes
Acidanthera
Acidaspis
Acieral
Acilius
Acineta
Acinetae
Acinetaria
Acinetina
Acipenser
Acipenseres
Acipenseridae
Acipenseroidei
Acis
Aclemon
Acmaea
Acmaeidae
Acmispon
Acnida
Acocanthera
Acoela
Acoelomata
Acoelomi
Acoemetae
Acoemeti
Acoemetic
Acolapissa
Acolhua
Acolhuan
Acoma
Aconitum
Acontias
Acontius
Acorus
Acousticon
Acrab
Acraeinae
Acrania
Acrasiaceae
Acrasiales
Acrasida
Acrasieae
Acraspeda
Acredula
Acrididae
Acridiidae
Acridium
Acrisius
Acrita
Acroa
Acrobates
Acrocarpi
Acrocera
Acroceratidae
Acroceraunian
Acroceridae
Acrochordidae
Acrochordinae
Acroclinium
Acrocomia
Acrodus
Acrogynae
Acromyodi
Acronycta
Acropora
Acrosticheae
Acrostichum
Acrothoracica
Acrotreta
Acrotretidae
Acrux
Acrydium
Actaea
Actaeaceae
Actaeon
Actaeonidae
Actiad
Actian
Actinia
Actiniaria
Actinidia
Actinidiaceae
Actiniomorpha
Actinistia
Actinobacillus
Actinocrinidae
Actinocrinus
Actinoida
Actinoidea
Actinomyces
Actinomycetaceae
Actinomycetales
Actinomyxidia
Actinomyxidiida
Actinonema
Actinophrys
Actinopoda
Actinopteri
Actinopterygii
Actinosphaerium
Actinozoa
Actipylea
Actium
Acts
Acuan
Acubens
Aculeata
Acutilinguae
Ada
Adad
Adai
Adaize
Adam
Adamastor
Adamhood
Adamic
Adamical
Adamically
Adamite
Adamitic
Adamitical
Adamitism
Adamsia
Adansonia
Adapa
Adapis
Adar
Adda
Addie
Addisonian
Addisoniana
Addressograph
Addu
Addy
Ade
Adela
Adelaide
Adelarthra
Adelarthrosomata
Adelbert
Adelea
Adeleidae
Adelges
Adelia
Adelina
Adeline
Adeliza
Adelochorda
Adelops
Adelphi
Adelphian
Adelphoi
Adenanthera
Adenophora
Adenostoma
Adeodatus
Adeona
Adephaga
Adessenarian
Adhafera
Adhara
Adiantum
Adib
Adicea
Adiel
Adigei
Adighe
Adigranth
Adin
Adinida
Adirondack
Adlai
Adlumia
Adolph
Adolphus
Adonai
Adonean
Adonia
Adoniad
Adonian
Adonic
Adoniram
Adonis
Adorantes
Adoretus
Adoxa
Adoxaceae
Adramelech
Adrammelech
Adrenalin
Adrian
Adriana
Adriatic
Adrienne
Adullam
Adullamite
Advaita
Advent
Adventism
Adventist
Aeacides
Aeacus
Aeaean
Aechmophorus
Aecidiaceae
Aecidiomycetes
Aedes
Aegean
Aegeriidae
Aegialitis
Aegina
Aeginetan
Aeginetic
Aegipan
Aegisthus
Aegithalos
Aegithognathae
Aegle
Aegopodium
Aeluroidea
Aeolia
Aeolian
Aeolic
Aeolicism
Aeolidae
Aeolididae
Aeolis
Aeolism
Aeolist
Aepyceros
Aepyornis
Aepyornithidae
Aepyornithiformes
Aequi
Aequian
Aequiculi
Aequipalpia
Aerides
Aerobacter
Aerobranchia
Aerocharidae
Aerope
Aerosol
Aeschylean
Aeschynanthus
Aeschynomene
Aesculaceae
Aesculapian
Aesculapius
Aesculus
Aesopian
Aesopic
Aestii
Aethionema
Aethusa
Aetian
Aetobatidae
Aetobatus
Aetolian
Aetomorphae
Aetosaurus
Afar
Afenil
Afghan
Afifi
Aframerican
Afrasia
Afrasian
Afric
African
Africana
Africanism
Africanist
Africanization
Africanize
Africanoid
Africanthropus
Afridi
Afrikaans
Afrikander
Afrikanderdom
Afrikanderism
Afrikaner
Afrogaea
Afrogaean
Afshah
Afshar
Aftonian
Afzelia
Agaces
Agade
Agag
Agalena
Agalenidae
Agalinis
Agama
Agamae
Agamemnon
Agamidae
Aganice
Aganippe
Agao
Agaonidae
Agapanthus
Agapemone
Agapemonian
Agapemonist
Agapemonite
Agapetidae
Agapornis
Agaricales
Agaricus
Agaristidae
Agarum
Agastache
Agastreae
Agatha
Agathaea
Agathaumas
Agathis
Agathosma
Agau
Agave
Agawam
Agaz
Agdistis
Agelacrinites
Agelacrinitidae
Agelaius
Agelaus
Agena
Ageratum
Aggie
Aggregata
Aggregatae
Aghan
Aghlabite
Aghorapanthi
Aghori
Agialid
Agib
Agiel
Agkistrodon
Aglaia
Aglaonema
Aglaos
Aglaspis
Aglauros
Aglipayan
Aglipayano
Aglossa
Aglypha
Aglyphodonta
Aglyphodontia
Agnatha
Agnathostomata
Agnes
Agnoetae
Agnoete
Agnoetism
Agnoite
Agnostus
Agnotozoic
Agoniatites
Agonista
Agonostomus
Agra
Agrania
Agrapha
Agrauleum
Agrilus
Agrimonia
Agriochoeridae
Agriochoerus
Agrionia
Agrionidae
Agriotes
Agriotypidae
Agriotypus
Agromyza
Agromyzidae
Agropyron
Agrostemma
Agrostis
Agrotis
Aguacateca
Agudist
Agyieus
Ah
Ahantchuyuk
Ahepatokla
Ahet
Ahir
Ahmadiya
Ahmed
Ahmet
Ahnfeltia
Ahom
Ahousaht
Ahrendahronon
Ahriman
Ahrimanian
Aht
Ahtena
Aias
Aiawong
Aidenn
Aides
Aigialosauridae
Aigialosaurus
Ailanthus
Aileen
Ailie
Ailuridae
Ailuroidea
Ailuropoda
Ailuropus
Ailurus
Aimak
Aimee
Aimore
Ainu
Aira
Airedale
Aissaoua
Aissor
Aistopoda
Aistopodes
Aitkenite
Aitutakian
Aix
Aizoaceae
Aizoon
Ajaja
Ajatasatru
Ajuga
Aka
Akal
Akali
Akamnik
Akan
Akanekunik
Akania
Akaniaceae
Akawai
Akebia
Akha
Akhissar
Akhlame
Akhmimic
Akim
Akiskemikinik
Akiyenik
Akka
Akkad
Akkadian
Akkadist
Akontae
Akoulalion
Akra
Akrabattine
Aktistetae
Aktistete
Aktivismus
Aktivist
Akwapim
Al
Alabama
Alabaman
Alabamian
Alactaga
Aladdin
Aladdinize
Aladfar
Aladinist
Alain
Alaki
Alala
Alamanni
Alamannian
Alamannic
Alan
Alangiaceae
Alangium
Alans
Alarbus
Alaria
Alaric
Alarodian
Alascan
Alaska
Alaskan
Alastair
Alaster
Alauda
Alaudidae
Alaunian
Alawi
Alb
Albainn
Alban
Albanenses
Albanensian
Albania
Albanian
Albany
Albatros
Alberene
Albert
Alberta
Albertina
Albertine
Albertinian
Albertist
Alberto
Albi
Albian
Albigenses
Albigensian
Albigensianism
Albin
Albion
Albireo
Albizzia
Albococcus
Alboin
Albrecht
Albright
Albruna
Albuca
Albuginaceae
Albyn
Alca
Alcaaba
Alcae
Alcaic
Alcaligenes
Alcalzar
Alcantara
Alcantarines
Alcedines
Alcedinidae
Alcedininae
Alcedo
Alcelaphus
Alces
Alchemilla
Alchornea
Alcibiadean
Alcicornium
Alcidae
Alcippe
Alcor
Alcoran
Alcoranic
Alcoranist
Alcotate
Alcuinian
Alcyonacea
Alcyonaria
Alcyone
Alcyones
Alcyoniaceae
Alcyonium
Aldebaran
Alderamin
Alderney
Aldhafara
Aldhafera
Aldine
Aldrovanda
Aldus
Alea
Alebion
Aleck
Alectoria
Alectorides
Alectoris
Alectoromorphae
Alectoropodes
Alectrion
Alectrionidae
Alectryon
Alejandro
Alemanni
Alemannian
Alemannic
Alemannish
Alemite
Alencon
Aleochara
Aleppine
Aleppo
Alethea
Aletris
Aleurites
Aleurobius
Aleurodes
Aleurodidae
Aleut
Aleutian
Aleutic
Alex
Alexander
Alexandra
Alexandreid
Alexandrian
Alexandrianism
Alexandrina
Alexandrine
Alexas
Alexia
Alexian
Alexis
Alexius
Aleyrodes
Aleyrodidae
Alf
Alfirk
Alfred
Alfreda
Alfur
Alfurese
Alfuro
Algaroth
Algarsife
Algarsyf
Algebar
Algedi
Algenib
Algerian
Algerine
Algernon
Algic
Algieba
Algol
Algoman
Algomian
Algomic
Algonkian
Algonquian
Algonquin
Algorab
Algores
Algy
Alhagi
Alhambra
Alhambraic
Alhambresque
Alhena
Alibamu
Alicant
Alice
Alichino
Alicia
Alick
Alida
Alids
Alikuluf
Alikulufan
Aline
Alioth
Alisma
Alismaceae
Alismales
Alismataceae
Alison
Alister
Alix
Alkaid
Alkalurops
Alkanna
Alkaphrah
Alkes
Alkoran
Alkoranic
Allah
Allamanda
Allan
Allantoidea
Allasch
Alle
Alleghenian
Allegheny
Allen
Allentiac
Allentiacan
Allhallow
Allhallowtide
Alliaceae
Alliaria
Allie
Allies
Allionia
Allioniaceae
Allium
Allobroges
Allophylus
Allosaurus
Allotheria
Allotriognathi
Allworthy
Ally
Alma
Almach
Almain
Alman
Almerian
Almida
Almira
Almohad
Almohade
Almohades
Almon
Almoravid
Almoravide
Almoravides
Almuredin
Alnaschar
Alnascharism
Alnilam
Alnitak
Alnitham
Alnus
Aloadae
Alocasia
Alogian
Alois
Alonso
Alonsoa
Alonzo
Alopecias
Alopecurus
Alopias
Alopiidae
Alosa
Alouatta
Aloxite
Aloysia
Aloysius
Alpax
Alpen
Alphard
Alphean
Alphecca
Alpheratz
Alphonist
Alphonse
Alphonsine
Alphonsism
Alphonso
Alpian
Alpid
Alpine
Alpinia
Alpiniaceae
Alpinism
Alpinist
Alpujarra
Alsatia
Alsatian
Alshain
Alsinaceae
Alsine
Alsophila
Alstonia
Alstroemeria
Altaian
Altaic
Altaid
Altair
Altamira
Alternanthera
Alternaria
Althaea
Althea
Altica
Alticamelus
Altingiaceae
Aluco
Aluconidae
Aluconinae
Aludra
Alulim
Alumel
Alumnol
Alundum
Alur
Alvah
Alvan
Alveolites
Alvin
Alvina
Alvissmal
Alya
Alyssum
Alytes
Amabel
Amadi
Amadis
Amaethon
Amafingo
Amahuaca
Amakosa
Amalfian
Amalfitan
Amalings
Amalrician
Amampondo
Amanda
Amandus
Amanist
Amanita
Amanitopsis
Amapondo
Amara
Amarantaceae
</details>

Output:

```
 vellum set --sorted 1000.txt 1000.fst
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10c7906]

goroutine 1 [running]:
github.com/couchbaselabs/vellum.(*Builder).optimize(0xc42006a180, 0x0, 0x6, 0xff7)
	/Users/mschoch/go/src/github.com/couchbaselabs/vellum/builder.go:165 +0x26
github.com/couchbaselabs/vellum.(*Builder).Insert(0xc42006a180, 0xc4200c1009, 0x7, 0xff7, 0x0, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/couchbaselabs/vellum/builder.go:83 +0x141
github.com/couchbaselabs/vellum/cmd/vellum/cmd.glob..func8(0x1266700, 0xc420016720, 0x2, 0x3, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/couchbaselabs/vellum/cmd/vellum/cmd/set.go:66 +0x22a
github.com/couchbaselabs/vellum/vendor/github.com/spf13/cobra.(*Command).execute(0x1266700, 0xc420016690, 0x3, 0x3, 0x1266700, 0xc420016690)
	/Users/mschoch/go/src/github.com/couchbaselabs/vellum/vendor/github.com/spf13/cobra/command.go:644 +0x3ef
github.com/couchbaselabs/vellum/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x12664e0, 0xc42006a058, 0x0, 0x1137c8b)
	/Users/mschoch/go/src/github.com/couchbaselabs/vellum/vendor/github.com/spf13/cobra/command.go:734 +0x339
github.com/couchbaselabs/vellum/vendor/github.com/spf13/cobra.(*Command).Execute(0x12664e0, 0x6, 0xc420047f00)
	/Users/mschoch/go/src/github.com/couchbaselabs/vellum/vendor/github.com/spf13/cobra/command.go:693 +0x2b
github.com/couchbaselabs/vellum/cmd/vellum/cmd.Execute()
	/Users/mschoch/go/src/github.com/couchbaselabs/vellum/cmd/vellum/cmd/root.go:36 +0x31
main.main()
	/Users/mschoch/go/src/github.com/couchbaselabs/vellum/cmd/vellum/main.go:20 +0x20
```

**Comment by mschoch** [comment]
Oddly, on this input file, it crashes while inserting: `Aesopic`

But, files with identical inputs up to and include `Aesopic` but fewer entries after it seem to work.  Still working on a simpler reproduction.

**Comment by mschoch** [comment]
Smallest input file that causes panic is first 893 lines:

<details>
A
Aani
Aaron
Aaronic
Aaronical
Aaronite
Aaronitic
Aaru
Ab
Ababdeh
Ababua
Abadite
Abama
Abanic
Abantes
Abarambo
Abaris
Abasgi
Abassin
Abatua
Abba
Abbadide
Abbasside
Abbie
Abby
Abderian
Abderite
Abdiel
Abdominales
Abe
Abel
Abelia
Abelian
Abelicea
Abelite
Abelmoschus
Abelonian
Abencerrages
Aberdeen
Aberdonian
Aberia
Abhorson
Abie
Abies
Abietineae
Abiezer
Abigail
Abipon
Abitibi
Abkhas
Abkhasian
Ablepharus
Abnaki
Abner
Abo
Abobra
Abongo
Abraham
Abrahamic
Abrahamidae
Abrahamite
Abrahamitic
Abram
Abramis
Abranchiata
Abrocoma
Abroma
Abronia
Abrus
Absalom
Absaroka
Absi
Absyrtus
Abu
Abundantia
Abuta
Abutilon
Abyssinian
Acacia
Acacian
Academic
Academus
Acadia
Acadian
Acadie
Acaena
Acalepha
Acalephae
Acalypha
Acalypterae
Acalyptrata
Acalyptratae
Acamar
Acanthaceae
Acantharia
Acanthia
Acanthocephala
Acanthocephali
Acanthocereus
Acanthodea
Acanthodei
Acanthodes
Acanthodidae
Acanthodii
Acanthodini
Acantholimon
Acanthomeridae
Acanthopanax
Acanthophis
Acanthopteri
Acanthopterygii
Acanthuridae
Acanthurus
Acarapis
Acarida
Acaridea
Acarina
Acarus
Acastus
Accipiter
Accipitres
Aceldama
Acemetae
Acemetic
Acephala
Acephali
Acephalina
Acephalite
Acer
Aceraceae
Acerae
Acerata
Acerates
Aceratherium
Acerbas
Acestes
Acetabularia
Acetobacter
Achaean
Achaemenian
Achaemenid
Achaemenidae
Achaemenidian
Achaenodon
Achaeta
Achagua
Achakzai
Achamoth
Achango
Achariaceae
Achariaceous
Achates
Achatina
Achatinella
Achatinidae
Achen
Achernar
Acheronian
Acherontic
Acherontical
Achetidae
Acheulean
Achillea
Achillean
Achilleid
Achillize
Achimenes
Achinese
Achitophel
Achlamydeae
Achmetha
Acholoe
Achomawi
Achordata
Achorion
Achras
Achroanthes
Achromatiaceae
Achromatium
Achromobacter
Achromobacterieae
Achuas
Achyranthes
Achyrodes
Acidanthera
Acidaspis
Acieral
Acilius
Acineta
Acinetae
Acinetaria
Acinetina
Acipenser
Acipenseres
Acipenseridae
Acipenseroidei
Acis
Aclemon
Acmaea
Acmaeidae
Acmispon
Acnida
Acocanthera
Acoela
Acoelomata
Acoelomi
Acoemetae
Acoemeti
Acoemetic
Acolapissa
Acolhua
Acolhuan
Acoma
Aconitum
Acontias
Acontius
Acorus
Acousticon
Acrab
Acraeinae
Acrania
Acrasiaceae
Acrasiales
Acrasida
Acrasieae
Acraspeda
Acredula
Acrididae
Acridiidae
Acridium
Acrisius
Acrita
Acroa
Acrobates
Acrocarpi
Acrocera
Acroceratidae
Acroceraunian
Acroceridae
Acrochordidae
Acrochordinae
Acroclinium
Acrocomia
Acrodus
Acrogynae
Acromyodi
Acronycta
Acropora
Acrosticheae
Acrostichum
Acrothoracica
Acrotreta
Acrotretidae
Acrux
Acrydium
Actaea
Actaeaceae
Actaeon
Actaeonidae
Actiad
Actian
Actinia
Actiniaria
Actinidia
Actinidiaceae
Actiniomorpha
Actinistia
Actinobacillus
Actinocrinidae
Actinocrinus
Actinoida
Actinoidea
Actinomyces
Actinomycetaceae
Actinomycetales
Actinomyxidia
Actinomyxidiida
Actinonema
Actinophrys
Actinopoda
Actinopteri
Actinopterygii
Actinosphaerium
Actinozoa
Actipylea
Actium
Acts
Acuan
Acubens
Aculeata
Acutilinguae
Ada
Adad
Adai
Adaize
Adam
Adamastor
Adamhood
Adamic
Adamical
Adamically
Adamite
Adamitic
Adamitical
Adamitism
Adamsia
Adansonia
Adapa
Adapis
Adar
Adda
Addie
Addisonian
Addisoniana
Addressograph
Addu
Addy
Ade
Adela
Adelaide
Adelarthra
Adelarthrosomata
Adelbert
Adelea
Adeleidae
Adelges
Adelia
Adelina
Adeline
Adeliza
Adelochorda
Adelops
Adelphi
Adelphian
Adelphoi
Adenanthera
Adenophora
Adenostoma
Adeodatus
Adeona
Adephaga
Adessenarian
Adhafera
Adhara
Adiantum
Adib
Adicea
Adiel
Adigei
Adighe
Adigranth
Adin
Adinida
Adirondack
Adlai
Adlumia
Adolph
Adolphus
Adonai
Adonean
Adonia
Adoniad
Adonian
Adonic
Adoniram
Adonis
Adorantes
Adoretus
Adoxa
Adoxaceae
Adramelech
Adrammelech
Adrenalin
Adrian
Adriana
Adriatic
Adrienne
Adullam
Adullamite
Advaita
Advent
Adventism
Adventist
Aeacides
Aeacus
Aeaean
Aechmophorus
Aecidiaceae
Aecidiomycetes
Aedes
Aegean
Aegeriidae
Aegialitis
Aegina
Aeginetan
Aeginetic
Aegipan
Aegisthus
Aegithalos
Aegithognathae
Aegle
Aegopodium
Aeluroidea
Aeolia
Aeolian
Aeolic
Aeolicism
Aeolidae
Aeolididae
Aeolis
Aeolism
Aeolist
Aepyceros
Aepyornis
Aepyornithidae
Aepyornithiformes
Aequi
Aequian
Aequiculi
Aequipalpia
Aerides
Aerobacter
Aerobranchia
Aerocharidae
Aerope
Aerosol
Aeschylean
Aeschynanthus
Aeschynomene
Aesculaceae
Aesculapian
Aesculapius
Aesculus
Aesopian
Aesopic
Aestii
Aethionema
Aethusa
Aetian
Aetobatidae
Aetobatus
Aetolian
Aetomorphae
Aetosaurus
Afar
Afenil
Afghan
Afifi
Aframerican
Afrasia
Afrasian
Afric
African
Africana
Africanism
Africanist
Africanization
Africanize
Africanoid
Africanthropus
Afridi
Afrikaans
Afrikander
Afrikanderdom
Afrikanderism
Afrikaner
Afrogaea
Afrogaean
Afshah
Afshar
Aftonian
Afzelia
Agaces
Agade
Agag
Agalena
Agalenidae
Agalinis
Agama
Agamae
Agamemnon
Agamidae
Aganice
Aganippe
Agao
Agaonidae
Agapanthus
Agapemone
Agapemonian
Agapemonist
Agapemonite
Agapetidae
Agapornis
Agaricales
Agaricus
Agaristidae
Agarum
Agastache
Agastreae
Agatha
Agathaea
Agathaumas
Agathis
Agathosma
Agau
Agave
Agawam
Agaz
Agdistis
Agelacrinites
Agelacrinitidae
Agelaius
Agelaus
Agena
Ageratum
Aggie
Aggregata
Aggregatae
Aghan
Aghlabite
Aghorapanthi
Aghori
Agialid
Agib
Agiel
Agkistrodon
Aglaia
Aglaonema
Aglaos
Aglaspis
Aglauros
Aglipayan
Aglipayano
Aglossa
Aglypha
Aglyphodonta
Aglyphodontia
Agnatha
Agnathostomata
Agnes
Agnoetae
Agnoete
Agnoetism
Agnoite
Agnostus
Agnotozoic
Agoniatites
Agonista
Agonostomus
Agra
Agrania
Agrapha
Agrauleum
Agrilus
Agrimonia
Agriochoeridae
Agriochoerus
Agrionia
Agrionidae
Agriotes
Agriotypidae
Agriotypus
Agromyza
Agromyzidae
Agropyron
Agrostemma
Agrostis
Agrotis
Aguacateca
Agudist
Agyieus
Ah
Ahantchuyuk
Ahepatokla
Ahet
Ahir
Ahmadiya
Ahmed
Ahmet
Ahnfeltia
Ahom
Ahousaht
Ahrendahronon
Ahriman
Ahrimanian
Aht
Ahtena
Aias
Aiawong
Aidenn
Aides
Aigialosauridae
Aigialosaurus
Ailanthus
Aileen
Ailie
Ailuridae
Ailuroidea
Ailuropoda
Ailuropus
Ailurus
Aimak
Aimee
Aimore
Ainu
Aira
Airedale
Aissaoua
Aissor
Aistopoda
Aistopodes
Aitkenite
Aitutakian
Aix
Aizoaceae
Aizoon
Ajaja
Ajatasatru
Ajuga
Aka
Akal
Akali
Akamnik
Akan
Akanekunik
Akania
Akaniaceae
Akawai
Akebia
Akha
Akhissar
Akhlame
Akhmimic
Akim
Akiskemikinik
Akiyenik
Akka
Akkad
Akkadian
Akkadist
Akontae
Akoulalion
Akra
Akrabattine
Aktistetae
Aktistete
Aktivismus
Aktivist
Akwapim
Al
Alabama
Alabaman
Alabamian
Alactaga
Aladdin
Aladdinize
Aladfar
Aladinist
Alain
Alaki
Alala
Alamanni
Alamannian
Alamannic
Alan
Alangiaceae
Alangium
Alans
Alarbus
Alaria
Alaric
Alarodian
Alascan
Alaska
Alaskan
Alastair
Alaster
Alauda
Alaudidae
Alaunian
Alawi
Alb
Albainn
Alban
Albanenses
Albanensian
Albania
Albanian
Albany
Albatros
Alberene
Albert
Alberta
Albertina
Albertine
Albertinian
Albertist
Alberto
Albi
Albian
Albigenses
Albigensian
Albigensianism
Albin
Albion
Albireo
Albizzia
Albococcus
Alboin
Albrecht
Albright
Albruna
Albuca
Albuginaceae
Albyn
Alca
Alcaaba
Alcae
Alcaic
Alcaligenes
Alcalzar
Alcantara
Alcantarines
Alcedines
Alcedinidae
Alcedininae
Alcedo
Alcelaphus
Alces
Alchemilla
Alchornea
Alcibiadean
Alcicornium
Alcidae
Alcippe
Alcor
Alcoran
Alcoranic
Alcoranist
Alcotate
Alcuinian
Alcyonacea
Alcyonaria
Alcyone
Alcyones
Alcyoniaceae
Alcyonium
Aldebaran
Alderamin
Alderney
Aldhafara
Aldhafera
Aldine
Aldrovanda
Aldus
Alea
Alebion
Aleck
Alectoria
Alectorides
Alectoris
Alectoromorphae
Alectoropodes
Alectrion
Alectrionidae
Alectryon
Alejandro
Alemanni
Alemannian
Alemannic
Alemannish
Alemite
Alencon
Aleochara
Aleppine
Aleppo
Alethea
Aletris
Aleurites
Aleurobius
Aleurodes
Aleurodidae
Aleut
Aleutian
Aleutic
Alex
Alexander
Alexandra
Alexandreid
Alexandrian
Alexandrianism
Alexandrina
Alexandrine
Alexas
Alexia
Alexian
Alexis
Alexius
Aleyrodes
Aleyrodidae
Alf
Alfirk
Alfred
Alfreda
Alfur
Alfurese
Alfuro
Algaroth
Algarsife
Algarsyf
Algebar
Algedi
Algenib
Algerian
Algerine
Algernon
Algic
Algieba
Algol
Algoman
Algomian
Algomic
Algonkian
Algonquian
Algonquin
Algorab
Algores
Algy
Alhagi
Alhambra
Alhambraic
Alhambresque
Alhena
Alibamu
Alicant
Alice
Alichino
Alicia
Alick
Alida
Alids
Alikuluf
Alikulufan
Aline
Alioth
Alisma
Alismaceae
Alismales
Alismataceae
Alison
Alister
Alix
Alkaid
Alkalurops
Alkanna
Alkaphrah
Alkes
Alkoran
Alkoranic
Allah
Allamanda
Allan
Allantoidea
Allasch
Alle
Alleghenian
Allegheny
Allen
Allentiac
Allentiacan
Allhallow
Allhallowtide
Alliaceae
Alliaria
Allie
Allies
Allionia
Allioniaceae
Allium
Allobroges
Allophylus
Allosaurus
Allotheria
Allotriognathi
Allworthy
Ally
Alma
Almach
Almain
Alman
Almerian
Almida
Almira
</details>

**Comment by mschoch** [comment]
Ah, looks like bug in my use of the scanner.  We do not own the bytes returned, so we must make a copy.
